name: 'Discord Notifier'

description: 'Send message notifications to Discord'

inputs:
    webhookUrl:
        description: 'Discord Webhook URL'
        required: true
    status:
        description: 'Status of the build'
        required: true
    projectName:
        description: 'Name of the project'
        required: true
    color:
        description: 'Color of the embed'
        required: false

runs:
    using: 'node20'
    main: 'index.js'
